// <auto-generated />
using System;
using Invest.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invest.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Invest.API.Models.Cotista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cotistas");
                });

            modelBuilder.Entity("Invest.API.Models.Operacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CotistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdCotas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorCota")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CotistaId");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("Invest.API.Models.Operacao", b =>
                {
                    b.HasOne("Invest.API.Models.Cotista", "Cotista")
                        .WithMany()
                        .HasForeignKey("CotistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotista");
                });
#pragma warning restore 612, 618
        }
    }
}
